### ISSUE TITLE
Vpnhood didnt connect anyway

### ISSUE THREAD

**Issue by kamaka1376** [vpnhood/VpnHood#158]
Hello
I used vpnhood for more than a month but from last night my servers got an error and they didnt connect to the server
I tried with several linux vps and the problem still exist
I already tried with console.vpnhood.com and tried with configure it manually no one connect please solve this issue .
Sometimes i got address already in use error both in website panel and in manually when i run it in port 443 and when i changed port to another port the server has been run and after a minute of trying to connect this error displayed :
`2022/11/12 14:44:47.177 | Error | Server => RemoteEp: 5.*.*.104:8537
 System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.CancellationToken.ThrowIfCancellationRequested()
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(So                                                                                         cketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.                                                                                         Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHa                                                                                         ndshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 m                                                                                         inSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter ada                                                                                         pter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAda                                                                                         pter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at VpnHood.Server.TcpHost.ProcessClient(TcpClient tcpClient, CancellationTok                                                                                         en cancellationToken) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Ser                                                                                         ver\TcpHost.cs:line 147

2022/11/12 14:46:29.427 | Error | Server => RemoteEp: 5.*.*.104:8540
 System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.CancellationToken.ThrowIfCancellationRequested()
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(So                                                                                         cketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.                                                                                         Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHa                                                                                         ndshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 m                                                                                         inSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter ada                                                                                         pter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAda                                                                                         pter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at VpnHood.Server.TcpHost.ProcessClient(TcpClient tcpClient, CancellationTok                                                                                         en cancellationToken) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Ser                                                                                         ver\TcpHost.cs:line 147`

**Comment by bobvhood** [comment]
This is not the error. Please share the full server log. You can also send your server credential to us with an access key so we can check it out. support@vpnhood.com

**Comment by kamaka1376** [comment]
@bobvhood Done please check your email

**Comment by bobvhood** [comment]
We had an issue in our access server. Please try it again and let us know the result

**Comment by kamaka1376** [comment]
Hello everything is fine now thank you very much

**Comment by kamaka1376** [comment]
If you develope your app for ios we can use your awesome app in all devices
Is that possible?

**Comment by bobvhood** [comment]
> iOS
I hope we do that one day.
#28

**Comment by 0xBF90E913** [comment]
@bobvhood time has come
