### ISSUE TITLE
Failing to connect network is unreachable 

### ISSUE THREAD

**Issue by joephalex** [vpnhood/VpnHood#176]
I did setup the access server and it's working fine but there are occasions where I get this exception from the Android App demo showing network is unreachable. 

{System.Net.Sockets.SocketException (0x80004005): Network is unreachable  at System.Net.Sockets.SocketAsyncResult.CheckIfThrowDelayedException () [0x00014] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/System/System.Net.Sockets/SocketAsyncResult.cs:127   at System.Net.Sockets.Socket.EndConnect (System.IAsyncResult asyncResult) [0x0002c] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/System/System.Net.Sockets/Socket.cs:1214   at System.Net.Sockets.TcpClient.EndConnect (System.IAsyncResult asyncResult) [0x00006] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/System/net/System/Net/Sockets/TCPClient.cs:393   at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x00019] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/FutureFactory.cs:538 --- End of stack trace from previous location where exception was thrown ---  at VpnHood.Common.Util.RunTask (System.Threading.Tasks.Task task, System.TimeSpan timeout, System.Threading.CancellationToken cancellationToken) [0x00133] in <ead70cfb86564e51b6b7d95f61ba0202>:0   at VpnHood.Client.VpnHoodClient.GetSslConnectionToServer (Microsoft.Extensions.Logging.EventId eventId, System.Threading.CancellationToken cancellationToken) [0x002ff] in <e2cd7e7c444649629797129cc63a4478>:0   at VpnHood.Client.VpnHoodClient.ConnectInternal (System.Threading.CancellationToken cancellationToken, System.Boolean redirecting) [0x0008a] in <e2cd7e7c444649629797129cc63a4478>:0   at VpnHood.Client.VpnHoodClient.Connect () [0x00220] in <e2cd7e7c444649629797129cc63a4478>:0   at *.Droid.MainActivity.ConnectTask_new (System.Threading.CancellationToken ct) [0x00282]

Then when I check from the server when I am trying to connect I do see this error 

2022/11/30 07:32:37.192 | Error | Server => RemoteEp: *.*.*.*:39023
 System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at VpnHood.Server.TcpHost.ProcessClient(TcpClient tcpClient, CancellationToken cancellationToken) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Server\TcpHost.cs:line 18

and this error 

2022/11/30 07:42:27.812 | Error | Server => RemoteEp: *.*.*.64:1095
 System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at VpnHood.Server.TcpHost.ProcessClient(TcpClient tcpClient, CancellationToken cancellationToken) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Server\TcpHost.cs:line 147

After couple of attempts trying to connect. It works fine. May I know how to overcome this issue please

**Comment by trudyhood** [comment]
These errors raise due to an entirely standard HTTPS connection request to the server and there is no trace of VPN activity at this phase.
I think it happens when you have an extremely unreliable or poor internet connection. Let us know if guess or find something else.

**Comment by joephalex** [comment]
Thank you for your reply. I am still trying to replicate the issue for the past few days. I will let you know the moment I have something.

**Comment by trudyhood** [comment]
Feel free to add any comments on this issue. We couldn't reproduce the problem.
