### ISSUE TITLE
Can't connect from Iran

### ISSUE THREAD

**Issue by techjoyment** [vpnhood/VpnHood#184]
I have a personal VPS and installed VPNhood with command lines. I've also added and edited appsettings.json file. This is what I get when I try to connect from Windows 10:

Info 
| 03:58:52.5412 |  | AppVersion: 2.4.320.0

Info 
| 03:58:52.5418 |  | Time: 2022-12-03 00:28:52Z

Info 
| 03:58:52.5421 |  | OS: Microsoft Windows NT 10.0.19045.0, 64-bit

Info 
| 03:58:52.5426 |  | UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.52

Info 
| 03:58:53.7874 |  | Country: Iran 

Info 
| 03:58:53.7876 |  | TokenId: **-84b0-22a20f5ad698, SupportId: **0

Trac 
| 03:58:53.7877 |  | Checking the Internet connection...

Info 
| 03:58:53.7879 |  | HttpTest: Started, Uri: https://www.google.com/, Timeout: 10000...

Info 
| 03:58:53.7881 |  | HttpTest: Started, Uri: https://www.quad9.net/, Timeout: 10000...

Info 
| 03:58:53.7883 |  | HttpTest: Started, Uri: https://www.microsoft.com/, Timeout: 10000...

Info 
| 03:58:54.3732 |  | HttpTest: Succeeded, Started, Uri: https://www.microsoft.com/.

Trac 
| 03:58:54.3749 |  | Checking the VpnServer ping...

Info 
| 03:58:54.3757 |  | PingTest: Started, RemoteAddress: 2602:fe90:2:2bb::c569, Timeout: 10000...

Erro 
| 03:58:54.3785 |  | PingTest: Failed! RemoteAddress: 2602:***:c569, Message: An exception occurred during a Ping request..

Warn 
| 03:58:54.3803 |  | Could not ping server! EndPoint: 2602:***:c569:8080, Error: An exception occurred during a Ping request.

Info => Client
| 03:58:54.3812 |  | UseUdpChannel: False, MinWorkerThreads: 8, CompletionPortThreads: 1

Info => Client
| 03:58:54.3821 |  | Client Version: 2.4.320.0, ClientId: **-ab75-2604e9b2ec50

Info => Client
| 03:58:54.3829 |  | Client is Connecting

Trac => Client
| 03:58:54.3838 | Session | Connecting to Server: 2602:***:c569:8080...

Erro => Client
| 03:58:54.3902 |  | Disposing. Error! System.Net.Sockets.SocketException (10051): A socket operation was attempted to an unreachable network.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at VpnHood.Common.Util.RunTask(Task task, TimeSpan timeout, CancellationToken cancellationToken) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Common\Util.cs:line 109
   at VpnHood.Client.VpnHoodClient.GetSslConnectionToServer(EventId eventId, CancellationToken cancellationToken) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Client\VpnHoodClient.cs:line 605
   at VpnHood.Client.VpnHoodClient.ConnectInternal(CancellationToken cancellationToken, Boolean redirecting) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Client\VpnHoodClient.cs:line 666
   at VpnHood.Client.VpnHoodClient.Connect() in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Client\VpnHoodClient.cs:line 210

Trac => Client
| 03:58:54.3913 |  | Disconnecting...

Info => Client
| 03:58:54.3923 |  | Client is Disconnecting

Trac => Client
| 03:58:54.3929 |  | Shutting down...

Trac => Client
| 03:58:54.3935 |  | Disposing TcpProxyHost...

Trac => Client
| 03:58:54.3941 |  | Disposing Tunnel...

Trac => Client
| 03:58:54.3946 |  | Disposing ProxyManager...

Trac => Client
| 03:58:54.3951 |  | Disposing Nat...

Info => Client
| 03:58:54.3956 |  | Client is Disposed

Info => Client
| 03:58:54.3961 |  | Bye Bye!

Erro 
| 03:58:54.3969 |  | A socket operation was attempted to an unreachable network.

**Comment by bobvhood** [comment]
> RemoteAddress: 2602:fe90:2:2bb::c569, Timeout: 10000...

Your server has IP6, and it is included in your AccessKey. Your client try to connect to your server via IPv6, but for some reason, it couldn't. 

Go to the access server and remove the IP from your server, and create the access key again.
Let me know if it doesn't work.
