### ISSUE TITLE
Throw System.IndexOutOfRangeException on the server side of Linux

### ISSUE THREAD

**Issue by rainwolfchen** [vpnhood/VpnHood#186]
After I install VpnHoodServer on Centos 7.6, systemctl status VpnHoodServer is exited, and the prompt is:

VpnHood. Server, Version=2.4.321.0, Culture=neutral, PublicKeyToken=null

2022/12/04 09:58:13.935 | Error | |

Stopped program because of exception! System. IndexOutOfRangeException Index was outside the bounds of the array.

One or more errors occurred. (Index was outside the bounds of the array.)

**Comment by trudyhood** [comment]
we didn't check that on centOS. Would you switch to Ubuntu? As far as I know, CentOS has been deprecated.

**Comment by rainwolfchen** [comment]
Considering that Centos still has a large number of vps, it is strongly recommended to consider supporting Centos deployment server.

**Comment by rainwolfchen** [comment]
v2.5.323 throw execption on centos.
[root@valued-beep-4 ~]# sudo /opt/VpnHoodServer/vhserver gen
[00:07:57.4400] info: [0]
      Using FileAccessServer. AccessFolder: /opt/VpnHoodServer/storage/access
[00:09:37.6814] fail: [0]
      Stopped program because of exception!
      System.InvalidOperationException: Sequence contains no elements
         at System.Linq.ThrowHelper.ThrowNoElementsException()
         at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
         at VpnHood.Server.Providers.FileAccessServerProvider.FileAccessServer.AccessItem_Create(IPEndPoint[] publicEndPoints, Int32 maxClientCount, String tokenName, Int32 maxTrafficByteCount, Nullable`1 expirationTime) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Server.Access\Providers\FileAccessServerProvider\FileAccessServer.cs:line 190
         at VpnHood.Server.App.FileAccessServerCommand.<>c__DisplayClass5_0.<<GenerateToken>b__1>d.MoveNext() in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Server.App.Net\FileAccessServerCommand.cs:line 100
      --- End of stack trace from previous location ---
         at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
         at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
         at VpnHood.Server.App.ServerApp.OnStart(String[] args) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Server.App.Net\ServerApp.cs:line 282
         at VpnHood.Common.AppBaseNet`1.Start(String[] args) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Common\AppBaseNet.cs:line 47
Sequence contains no elements

**Comment by trudyhood** [comment]
it looks the VpnHood could not find your public IP server by querying https://api.ipify.org?format=json
Please try to set the access token public IP using the -ep option. let me know the result if you are still working on VpnHood.

**Comment by rainwolfchen** [comment]
When i installed v2.4.321.0，"sudo /opt/VpnHoodServer/vhserver gen" was successful.
But when I installed v2.5.324, this command threw an exception:
[root@valued-beep-4 VpnHoodServer]# sudo /opt/VpnHoodServer/vhserver gen
[23:16:36.8284] info: [0]
      Using FileAccessServer. AccessFolder: /opt/VpnHoodServer/storage/access
[23:16:39.0612] fail: [0]
      Stopped program because of exception!
      System.InvalidOperationException: Sequence contains no elements
         at System.Linq.ThrowHelper.ThrowNoElementsException()
         at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
         at VpnHood.Server.Providers.FileAccessServerProvider.FileAccessServer.AccessItem_Create(IPEndPoint[] publicEndPoints, Int32 maxClientCount, String tokenName, Int32 maxTrafficByteCount, Nullable`1 expirationTime) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Server.Access\Providers\FileAccessServerProvider\FileAccessServer.cs:line 190
         at VpnHood.Server.App.FileAccessServerCommand.<>c__DisplayClass5_0.<<GenerateToken>b__1>d.MoveNext() in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Server.App.Net\FileAccessServerCommand.cs:line 100
      --- End of stack trace from previous location ---
         at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
         at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
         at VpnHood.Server.App.ServerApp.OnStart(String[] args) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Server.App.Net\ServerApp.cs:line 282
         at VpnHood.Common.AppBaseNet`1.Start(String[] args) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Common\AppBaseNet.cs:line 47
Sequence contains no elements

**Comment by rainwolfchen** [comment]
[root@valued-beep-4 VpnHoodServer]# /opt/VpnHoodServer/vhserver -ep
[23:22:38.5047] info: [0]
      Using FileAccessServer. AccessFolder: /opt/VpnHoodServer/storage/access
Specify --help for a list of available options and commands.
[23:22:40.7390] fail: [0]
      Stopped program because of exception!
      McMaster.Extensions.CommandLineUtils.UnrecognizedCommandParsingException: Unrecognized option '-ep'
         at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessUnexpectedArg(String argTypeName, String argValue)
         at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessOption(OptionArgument arg)
         at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessNext()
         at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.Process()
         at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Parse(String[] args)
         at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
         at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
         at VpnHood.Server.App.ServerApp.OnStart(String[] args) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Server.App.Net\ServerApp.cs:line 282
         at VpnHood.Common.AppBaseNet`1.Start(String[] args) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Common\AppBaseNet.cs:line 47
Unrecognized option '-ep'

**Comment by trudyhood** [comment]
You need to add an IP to your access key, so client can find the server and connect to it.
the -ep must be used with "gen" command.

/opt/VpnHoodServer/vhserver gen -ep YOUR_SERVER_PUBLIC_ADDRESS

**Comment by rainwolfchen** [comment]
/opt/VpnHoodServer/vhserver gen -ep YOUR_SERVER_PUBLIC_ADDRESS  was successful.
but /opt/VpnHoodServer/vhserver start failed, throw exception:
[root@valued-beep-4 v2.5.324]# /opt/VpnHoodServer/vhserver start
[13:30:12.5992] info: [0]
      Using FileAccessServer. AccessFolder: /opt/VpnHoodServer/storage/access
2022/12/14 13:30:13.518 | Info |  | Server
 VpnHood.Server, Version=2.5.324.0, Culture=neutral, PublicKeyToken=null

2022/12/14 13:30:13.580 | Error |  |
 Stopped program because of exception! System.IndexOutOfRangeException Index was outside the bounds of the array.

One or more errors occurred. (Index was outside the bounds of the array.)

**Comment by trudyhood** [comment]
Have you set your public IP instead YOUR_SERVER_PUBLIC_ADDRESS?

Please upgrade to version 2.6.326. in the new version, try both
/opt/VpnHoodServer/vhserver gen
/opt/VpnHoodServer/vhserver gen -ep <YOUR_SERVER_IP>

**Comment by rainwolfchen** [comment]
When I install version 2.6.326, command "/opt/VpnHoodServer/vhserver gen" runs successfully, but command "/opt/VpnHoodServer/vhserver start" still fails and throws the following exception:

[root@valued-beep-4 ~]# /opt/VpnHoodServer/vhserver start
[20:53:37.8231] info: [0]
      Using FileAccessServer. AccessFolder: /opt/VpnHoodServer/storage/access
2022/12/15 20:53:38.517 | Info |  | Server
 VpnHood.Server, Version=2.6.326.0, Culture=neutral, PublicKeyToken=null

2022/12/15 20:53:38.592 | Error |  |
 Stopped program because of exception! System.IndexOutOfRangeException Index was outside the bounds of the array.

One or more errors occurred. (Index was outside the bounds of the array.)

**Comment by trudyhood** [comment]
Is it possible to give us access to your server? support@vpnhood.com

**Comment by rainwolfchen** [comment]
Yes, I have sent relevant information to your email

**Comment by trudyhood** [comment]
@rainwolfchen 
Thank you for sharing your server. We have found the issue and fixed it for cent os. You can change the credential. 
The next version will not have this issue. Meanwhile, you can use the prerelease version:

```
sudo su -c "bash <( wget -qO- https://github.com/vpnhood/VpnHood/releases/download/v2.6.327-prerelease/VpnHoodServer-linux-x64.sh)"
```

**Comment by rainwolfchen** [comment]
Thank you very much. After testing, the version works normally.
