### ISSUE TITLE
Packets dropped! Error in processing channel received packets. Message: System.Net.Sockets.SocketException (10055): An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.

### ISSUE THREAD

**Issue by joephalex** [vpnhood/VpnHood#221]
Hi,

I was testing on my server and after awhile of using I started receiving this error then the server crashes  

"Packets dropped! Error in processing channel received packets. Message: System.Net.Sockets.SocketException (10055): An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."

2022-12-29 05:19:01.2926 | Error |  | Server => RemoteEp: *.*.*.67:9371 => SessionId: 12 
 Packets dropped! Error in processing channel received packets. Message: System.Net.Sockets.SocketException (10055): An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at VpnHood.Tunneling.Factory.SocketFactory.CreateUdpClient(AddressFamily addressFamily) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Tunneling\Factory\SocketFactory.cs:line 18
   at VpnHood.Tunneling.ProxyManager.<>c__DisplayClass37_0.<SendUdpPacket>b__0(String _) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Tunneling\ProxyManager.cs:line 200
   at VpnHood.Common.Collections.TimeoutDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Common\Collections\TimeoutDictionary.cs:line 41
   at VpnHood.Tunneling.ProxyManager.SendUdpPacket(IPPacket ipPacket) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Tunneling\ProxyManager.cs:line 185
   at VpnHood.Tunneling.ProxyManager.SendPacket(IPPacket ipPacket) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Tunneling\ProxyManager.cs:line 144
   at VpnHood.Tunneling.ProxyManager.SendPacket(IPPacket[] ipPackets) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Tunneling\ProxyManager.cs:line 120
   at VpnHood.Tunneling.Tunnel.Channel_OnPacketReceived(Object sender, ChannelPacketReceivedEventArgs e) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Tunneling\Tunnel.cs:line 259 

**For the server configuration I have used the default one**

2022-12-29 04:38:08.5271 | Info |  | Server 
 ServerConfig: {"Tracking":{"TrackClientIp":false,"TrackLocalPort":false,"TrackDestinationIp":false,"TrackDestinationPort":false},"TrackingOptions":{"TrackClientIp":false,"TrackLocalPort":false,"TrackDestinationIp":false,"TrackDestinationPort":false},"Session":{"Timeout":"01:00:00","UdpTimeout":"00:01:00","TcpTimeout":"00:15:00","IcmpTimeout":"00:00:30","SyncCacheSize":100000000,"SyncInterval":"00:20:00","MaxDatagramChannelCount":0,"MaxUdpPortCount":0,"TcpBufferSize":0},"SessionOptions":{"Timeout":"01:00:00","UdpTimeout":"00:01:00","TcpTimeout":"00:15:00","IcmpTimeout":"00:00:30","SyncCacheSize":100000000,"SyncInterval":"00:20:00","MaxDatagramChannelCount":0,"MaxUdpPortCount":0,"TcpBufferSize":0},"UdpPort":0,"ConfigCode":"00000000-0000-0000-0000-000000000000","TcpEndPoints":["0.0.0.0:443","[::]:443"],"UpdateStatusInterval":"00:02:00"}  

2022-12-29 04:38:08.5346 | Info |  | Server 
 Starting TcpHost...  

Do you think applying the appsettings.json from https://github.com/vpnhood/VpnHood/wiki/VpnHood-Server-Configuration will fix the issue

appsettings.json

{
  "RestAccessServer": null,
  "FileAccessServer": {
    "TcpEndPoints": [ "0.0.0.0:443", "[::]:443" ],
    "SslCertificatesPassword": null,
    "Tracking": {
      "TrackClientIp": false,
      "TrackLocalPort": false,
      "TrackDestinationIp": false,
      "TrackDestinationPort": false
    },
    "Session": {
      "Timeout": "01:00:00",
      "UdpTimeout": "00:00:01",
      "TcpTimeout": "00:15:00",
      "IcmpTimeout": "00:30:00",
      "MaxDatagramChannelCount": 8,
      "MaxUdpPortCount": 0,
      "TcpBufferSize": 8192
    }
  },
  "IsDiagnoseMode": false
}

And this [link ](https://confluence.atlassian.com/confkb/no-buffer-space-available-maximum-connections-reached-due-to-ephemeral-port-exhaustion-956142091.html)I did mention a solution for  this error code but I am not really sure

I am running on Windows server 2022 

I would really appreciate your feedback on how to solve the issue

**Comment by trudyhood** [comment]
It sounds like your server ran out of memory. How much does your server have memory?

**Comment by joephalex** [comment]
The server has 8gb of ram. During the time it happened it was 40% used

**Comment by trudyhood** [comment]
8gb is plenty much! do you know many users were connected that time?
does it happen again and again?
how long did you see that error?

please delete the session section in app settings to make sure it uses the
default. the MaxUdpPortCount and UdpTimeout are not configured correctly.

**Comment by joephalex** [comment]
The number of sessions were around 120 then it happened and suddenly I was unable to connect the server RDP anymore and I had to reboot the server.

That time I used the default values without having appsettings.json added inside the storage folder. 

This same issue happened again after rebooting the server and running the server again. Then I have decided to add the appsettings.json file and test again and now it's working fine.

So in this case would you suggest removing appsettings.json as it has the session section and relying again on the default settings by re-running the server again?

**Comment by trudyhood** [comment]
I have to update the doc. Please set the MaxUdpPortCount to 500 and delete other items in Session:

```json
"Session": {
      "MaxUdpPortCount": 500 
    }
````

**Comment by joephalex** [comment]
Happy new year :).  Thank you for reply, I will be applying it and I will let you know of the outcome

**Comment by trudyhood** [comment]
Have you managed to find the issue?

**Comment by joephalex** [comment]
I did apply your solutions and as well this one [https://confluence.atlassian.com/confkb/no-buffer-space-available-maximum-connections-reached-due-to-ephemeral-port-exhaustion-956142091.html](url) and I have been testing it for the past one week and so far everything seems to be working fine and I have not been encountered with this issue anymore
