### ISSUE TITLE
One server is shutted down

### ISSUE THREAD

**Issue by asoMansoury** [vpnhood/VpnHood#333]
After the server which was updated to the latest version, is shutted down, and I got this error on all clients.

Erro => Client
| 11:30:37.7782 |  | Disposing. Error! System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at VpnHood.Client.VpnHoodClient.GetTlsConnectionToServer(EventId eventId, CancellationToken cancellationToken) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Client\VpnHoodClient.cs:line 710
   at VpnHood.Client.VpnHoodClient.ConnectInternal(CancellationToken cancellationToken, Boolean redirecting) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Client\VpnHoodClient.cs:line 817
   at VpnHood.Client.VpnHoodClient.Connect() in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Client\VpnHoodClient.cs:line 252

**Comment by trudyhood** [comment]
please checks its TCP endpoints. this error indicates that the server does not listen. check the server log

**Comment by asoMansoury** [comment]
> please checks its TCP endpoints. this error indicates that the server does not listen. check the server log

Where is the server log?

**Comment by trudyhood** [comment]
https://github.com/vpnhood/VpnHood/discussions/290

**Comment by trudyhood** [comment]
check server.log

**Comment by asoMansoury** [comment]
> 

2023-05-18 08:06:20.4371 | Info |  | Server
 MinWorkerThreads: 2, MinCompletionPortThreads: 30

2023-05-18 08:06:20.4371 | Info |  | Server
 MaxWorkerThreads: 32767, MaxCompletionPortThreads: 65535

2023-05-18 08:06:20.4500 | Info |  | Server
 Starting ServerHost...

2023-05-18 08:06:20.4529 | Info |  | Server
 Start listening on UdpEndPoint: 135.*.*.141:7669

2023-05-18 08:06:20.4646 | Info |  | Server
 Start listening on UdpEndPoint: 2a01:***:0001:6579

2023-05-18 08:06:20.4646 | Info |  | Server
 Start listening on TcpEndPoint: 135.*.*.141:443

2023-05-18 08:06:20.4706 | Info |  | Server
 Start listening on TcpEndPoint: 2a01:***:0001:443

2023-05-18 08:06:20.4706 | Info |  | Server
 Server is ready!

**Comment by asoMansoury** [comment]
I checked again and I found that my IP address is blocked!!!

**Comment by trudyhood** [comment]
Based on the error message you provided, "An existing connection was forcibly closed by the remote host," it indicates that the remote host is reachable, but it is not actively listening on the specific port you are attempting to connect to. This refusal message typically (not always) originates from the server, indicating that it is reachable. If your server IP was blocked, you should get an "unreachable" or "timeout" error.

**Comment by asoMansoury** [comment]
> Based on the error message you provided, "An existing connection was forcibly closed by the remote host," it indicates that the remote host is reachable, but it is not actively listening on the specific port you are attempting to connect to. This refusal message typically (not always) originates from the server, indicating that it is reachable. If your server IP was blocked, you should get an "unreachable" or "timeout" error.

Hello, Thanks for your great supporting, after struggling with the server I found that the server was blocked!
thanks for you assistance.
