### ISSUE TITLE
When building a simple Android client using MAUI, throwing exceptions

### ISSUE THREAD

**Issue by demooooooo** [vpnhood/VpnHood#360]
![exception](https://github.com/vpnhood/VpnHood/assets/40201400/83aede85-4cb1-4b12-b2ed-501a3ada4215)
The framework is based on .net 6.0，Exception message content。

`{System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+AndroidCrypto+SslException: Exception of type 'Interop+AndroidCrypto+SslException' was thrown.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__175`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at VpnHood.Client.VpnHoodClient.GetTlsConnectionToServer(EventId eventId, CancellationToken cancellationToken)
   at VpnHood.Client.VpnHoodClient.ConnectInternal(CancellationToken cancellationToken, Boolean redirecting)
   at VpnHood.Client.VpnHoodClient.Connect()
 }`

**Comment by bobvhood** [comment]
Hi, Unfortunately, we haven't tested it with MAUI. However, I think there is something wrong with self-certificate validation. 
We don't know much more. We would be grateful if you share your experience with us if you get to sort it out.

**Comment by trudyhood** [comment]
Hi All, Could you fix this issue? It looks like the issue is serious:
https://github.com/dotnet/runtime/issues/84785

Let me know if you could fix this.
