### ISSUE TITLE
vpnhood windows client 423 errors

### ISSUE THREAD

**Issue by farzinsb** [vpnhood/VpnHood#387]
after updating to latest vpnhood client it crashes and won't start.
windows 10 version 22h2  ( build 19045 ) 

```
Application: VpnHoodClient.exe
CoreCLR Version: 7.0.1123.42427
.NET Version: 7.0.11
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.Extensions.Logging.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at VpnHood.Client.App.Win.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at VpnHood.Client.App.Win.App.Main()
```

`Faulting application name: VpnHoodClient.exe, version: 2023.9.27.1726, time stamp: 0x64e841c5
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3393, time stamp: 0x6b4de7c9
Exception code: 0xe0434352
Fault offset: 0x000000000002cf19
Faulting process id: 0x320c
Faulting application start time: 0x01d9f1cc8be839a3
Faulting application path: C:\Program Files\VpnHood\VpnHood\VpnHoodClient.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: fb7d9d1a-245a-4528-8788-31719288408f
Faulting package full name: 
Faulting package-relative application ID: `

**Comment by farzinsb** [comment]
I downgraded to Version: 3.0.416.169  and it started working with server 423.

 systemctl status VpnHoodServer
● VpnHoodServer.service - VpnHood Server
     Loaded: loaded (/etc/systemd/system/VpnHoodServer.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2023-09-28 01:22:37 EDT; 28min ago
   Main PID: 1390 (VpnHoodServer)
      Tasks: 16 (limit: 2220)
     Memory: 89.8M
        CPU: 1min 6.964s
     CGroup: /system.slice/VpnHoodServer.service
             └─1390 /opt/VpnHoodServer/v3.0.423/VpnHoodServer

Sep 28 01:22:37 hami9u.digik.wiki systemd[1]: Started VpnHood Server.

**Comment by trudyhood** [comment]
Yes, we have removed 423 and now working on it to find the issue in the published installation.

**Comment by trudyhood** [comment]
Thank you for reporting. Please check the update again and let me know if there are any more issues.
