### ISSUE TITLE
Installation broken

### ISSUE THREAD

**Issue by tkmw1985** [vpnhood/VpnHood#40]
Hello !  
it looks like the installation or the script is broken.

Ubuntu 20

/dev/fd/63: line 2: $'\r': command not found
/dev/fd/63: line 3: $'\r': command not found
Installation script for linux
/dev/fd/63: line 4: $'\r': command not found
Install .NET Runtime 5.0 for ubuntu/21.04 (y/n)?y
/dev/fd/63: line 5: $'\r': command not found
Auto Start (y/n)?y
/dev/fd/63: line 7: $'\r': command not found
/dev/fd/63: line 8: $'\r': command not found
/dev/fd/63: line 10: $'\r': command not found
/dev/fd/63: line 11: $'\r': command not found
/dev/fd/63: line 12: $'\r': command not found
/dev/fd/63: line 76: syntax error: unexpected end of file

**Comment by trudyhood** [comment]
Thank you for reporting the issue.
I have updated the Linux installation script to it should work for more Linux distribution. also these **$'\r': command not found"** has been solved too.
Please try again and let me know if you there any more issue.

**Comment by tkmw1985** [comment]
Another issue accured after installation completed !

The problem is that when i start command generating access key (sudo dotnet /opt/VpnHoodServer/launcher/run.dll gen)

sudo dotnet /opt/VpnHoodServer/launcher/run.dll gen
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application '/opt/VpnHoodServer/launcher/run.dll' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download

**Comment by mihaibarbulescu** [comment]
Hello!

> dotnet /opt/VpnHoodServer/launcher/run.dll gen
> Could not execute because the application was not found or a compatible .NET SDK is not installed.
> Possible reasons for this include:
> 
> * You intended to execute a .NET program:
>   The application '/opt/VpnHoodServer/launcher/run.dll' does not exist.
> * You intended to execute a .NET SDK command:
>   It was not possible to find any installed .NET SDKs.
>   Install a .NET SDK from:
>   https://aka.ms/dotnet-download

The same happens at my side upon attempting to generate an access key.
Likewise, the test was done on Ubuntu 20.04 (LTS) x64.
Just to confirm, the script did installed dotnet-runtime-50 and manual alias created, as can be seen below:

Installation script for linux
Set dotnet alias to .NET 5.0 (y/n)?y
Auto Start (y/n)?y
Warning: flag --classic ignored for strictly confined snap dotnet-runtime-50

dotnet-runtime-50 5.0.9 from Microsoft .NET Core (dotnetcore✓) installed
Added:
  - dotnet-runtime-50.dotnet as dotnet50
error: cannot find manual alias "dotnet" in any snap
Added:
  - dotnet-runtime-50.dotnet as dotnet

**Comment by tkmw1985** [comment]
First problem in the script  caused by syntax error  i guess. second one i don't know.

**Comment by mihaibarbulescu** [comment]
> First problem in the script caused by syntax error i guess. second one i don't know.

Hello,

Thank you for your reply.
The first problem did not happen at my side. As I tested after you reported and @trudyhood fixed it.
The second problem seems to be now happening for both me and you.

**Comment by mihaibarbulescu** [comment]
@tkmw1985 are you running Ubuntu 20.04 (LTS) or Ubuntu 20.10?

It seems that  .NET 5.0 is not supported on Ubuntu 20.10, according to https://docs.microsoft.com/en-us/dotnet/core/install/linux (see the Ubuntu section).

**Comment by trudyhood** [comment]
It looks dotnet installation runtime with snap is a mess: https://github.com/dotnet/core/issues/4446

I had to switch to NET-SDK latest/edge channel, I hope they fix this in NET 6.
Please use the following commands to fix that. Please let me know if there is any issue
```
sudo snap remove dotnet-runtime-50
sudo su -c "bash <( wget -qO- https://github.com/vpnhood/VpnHood/releases/latest/download/install-linux.sh)"
```

**Comment by mihaibarbulescu** [comment]
Hi @trudyhood 

I tested this in my droplet now. Here is the result:

# dotnet /opt/VpnHoodServer/launcher/run.dll gen
/opt/VpnHoodServer/publish.json

Launching 2.0.271/VpnHoodServer.dll!

2021-09-08 17:34:02.0042 | Info |   
 Initializing ResetAccessServer!, BaseUri: https://localhost:5001/api/access/, Authorization: True...  

2021-09-08 17:34:02.1345 | Info |   
 VpnHoodServer, Version=2.0.271.0, Culture=neutral, PublicKeyToken=null  

2021-09-08 17:34:02.1345 | Info |   
 OS: Unix 5.4.0.84, 64-bit
Linux version 5.4.0-84-generic (buildd@lgw01-amd64-050) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #94-Ubuntu SMP Thu Aug 26 20:27:37 UTC 2021  

Specify --help for a list of available options and commands.
2021-09-08 17:34:02.1990 | Error |   
 Stopped program because of exception! McMaster.Extensions.CommandLineUtils.UnrecognizedCommandParsingException: Unrecognized command or argument 'gen'
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessUnexpectedArg(String argTypeName, String argValue)
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessCommandOrParameter(CommandOrParameterArgument arg)
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessNext()
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.Process()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Parse(String[] args)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at VpnHood.Server.App.ServerApp.OnStart(String[] args) in C:\Users\Robert\Source\Repos\Vh\VpnHood\VpnHood.Server.App.Net\ServerApp.cs:line 210
   at VpnHood.Common.AppBaseNet`1.Start(String[] args) in C:\users\robert\source\repos\vh\vpnhood\VpnHood.Common\AppBaseNet.cs:line 113 

Unhandled exception. McMaster.Extensions.CommandLineUtils.UnrecognizedCommandParsingException: Unrecognized command or argument 'gen'
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessUnexpectedArg(String argTypeName, String argValue)
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessCommandOrParameter(CommandOrParameterArgument arg)
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessNext()
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.Process()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Parse(String[] args)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at VpnHood.Server.App.ServerApp.OnStart(String[] args) in C:\Users\Robert\Source\Repos\Vh\VpnHood\VpnHood.Server.App.Net\ServerApp.cs:line 210
   at VpnHood.Common.AppBaseNet`1.Start(String[] args) in C:\users\robert\source\repos\vh\vpnhood\VpnHood.Common\AppBaseNet.cs:line 113
   at VpnHood.Server.App.Program.Main(String[] args) in C:\Users\Robert\Source\Repos\Vh\VpnHood\VpnHood.Server.App.Net\Program.cs:line 10

I hope this helps to further debug.

Thank you!

**Comment by trudyhood** [comment]
@mihaibarbulescu
I have fixed it too. You see this error because it is using a RestAccessServer. To fix this open appsettings.json and replace it with this one (Remove RestBaseUrl)
{
  "EndPoint": "0.0.0.0:443",
  "IsDiagnoseMode": false
}

**Comment by mihaibarbulescu** [comment]
@trudyhood 
That fixed it, thank you!
