### ISSUE TITLE
what is happaning?

### ISSUE THREAD

**Issue by Keiser04** [vpnhood/VpnHood#514]
Info 
| 19:00:53.0321 |  | VpnHood Client is Connecting ...

Info 
| 19:00:53.0324 |  | AppVersion: 3.3.463.0

Info 
| 19:00:53.0324 |  | Time: 2024-04-11 17:00:53Z

Info 
| 19:00:53.0324 |  | OS: Microsoft Windows NT 10.0.22631.0, 64-bit

Info 
| 19:00:53.0324 |  | UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0

Info 
| 19:00:56.3160 |  | Country: Spain

Info 
| 19:00:56.3160 |  | TokenId: **-8adb-65a427b60f58, SupportId: **04

Info 
| 19:00:56.3214 |  | UserSettings: {
  "Logging": {
    "LogToConsole": true,
    "LogToFile": false,
    "LogVerbose": false,
    "LogAnonymous": true
  },
  "CultureCode": "en",
  "DefaultClientProfileId": "d9823e49-fb50-4a46-aacf-ba4d8d2e7860",
  "MaxReconnectCount": 2147483647,
  "MaxDatagramChannelCount": 4,
  "TunnelClientCountry": true,
  "IpGroupFilters": null,
  "IpGroupFiltersMode": "All",
  "CustomIpRanges": null,
  "AppFilters": null,
  "AppFiltersMode": "All",
  "UseUdpChannel": true,
  "DropUdpPackets": false,
  "ExcludeLocalNetwork": true,
  "PacketCaptureIncludeIpRanges": [
    "0.0.0.0-255.255.255.255",
    "::-ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff"
  ],
  "PacketCaptureExcludeIpRanges": [],
  "AllowAnonymousTracker": true
}

Trac 
| 19:00:56.3226 |  | Checking the Internet connection...

Info 
| 19:00:56.3249 |  | HttpTest: Started, Url: https://www.google.com/, Timeout: 10000...

Info 
| 19:00:56.3253 |  | HttpTest: Started, Url: https://www.quad9.net/, Timeout: 10000...

Info 
| 19:00:56.3255 |  | HttpTest: Started, Url: https://www.microsoft.com/, Timeout: 10000...

Info 
| 19:00:56.5074 |  | HttpTest: Succeeded, Url: https://www.google.com/.

Trac 
| 19:00:56.5076 |  | Checking the VpnServer ping...

Info 
| 19:00:56.5858 |  | PingTest: Started, RemoteAddress: 45.*.*.123, Timeout: 10000...

Info 
| 19:00:56.7483 |  | HttpTest: Succeeded, Url: https://www.microsoft.com/.

Info 
| 19:00:57.2960 |  | HttpTest: Succeeded, Url: https://www.quad9.net/.

Warn 
| 19:01:06.3630 |  | PingTest: Failed!, RemoteAddress: 45.*.*.123. Message: Status: TimedOut
Exception: System.Exception: Status: TimedOut
   at VpnHood.Client.Diagnosing.DiagnoseUtil.CheckPing(IPAddress ipAddress, Int32 timeout, Boolean anonymize) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Client\Diagnosing\DiagnoseUtil.cs:line 118

Warn 
| 19:01:06.3630 |  | Could not ping server! EndPoint: 45.*.*.123, Error: Status: TimedOut

Info => Client
| 19:01:06.3661 |  | UseUdpChannel: True, DropUdpPackets: False, ExcludeLocalNetwork: True, MinWorkerThreads: 12, CompletionPortThreads: 1

Info => Client
| 19:01:06.3661 |  | ClientVersion: 3.3.463.0, ClientProtocolVersion: 4, ClientId: **-b0cb-1b26e3057039

Info => Client
| 19:01:06.3661 |  | Client state is changed. NewState: Connecting

Trac => Client
| 19:01:06.4263 | Session | Sending a request. RequestCode: Hello, RequestId: 3559d56a-3f41-44ee-ae8f-09f87d8aad86:client

Trac => Client
| 19:01:06.4264 | Tcp | Connecting to Server... EndPoint: 45.*.*.123:443

Erro 
| 19:01:27.4401 | Session | Disposing...
Exception: VpnHood.Client.Exceptions.ConnectorEstablishException: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.
 ---> System.Net.Sockets.SocketException (10060): Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at VpnHood.Common.Utils.VhUtil.RunTask(Task task, TimeSpan timeout, CancellationToken cancellationToken) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Common\Utils\VhUtil.cs:line 114
   at VpnHood.Client.ConnectorServices.ConnectorService.GetTlsConnectionToServer(String streamId, CancellationToken cancellationToken) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Client\ConnectorServices\ConnectorService.cs:line 113
   --- End of inner exception stack trace ---
   at VpnHood.Client.ConnectorServices.ConnectorService.GetTlsConnectionToServer(String streamId, CancellationToken cancellationToken) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Client\ConnectorServices\ConnectorService.cs:line 134
   at VpnHood.Client.ConnectorServices.ConnectorService.SendRequest[T](Byte[] request, String requestId, CancellationToken cancellationToken) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Client\ConnectorServices\ConnectorService.cs:line 248
   at VpnHood.Client.ConnectorServices.ConnectorService.SendRequest[T](EventId eventId, ClientRequest request, CancellationToken cancellationToken)
   at VpnHood.Client.ConnectorServices.ConnectorService.SendRequest[T](EventId eventId, ClientRequest request, CancellationToken cancellationToken) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Client\ConnectorServices\ConnectorService.cs:line 210
   at VpnHood.Client.VpnHoodClient.SendRequest[T](ClientRequest request, CancellationToken cancellationToken)
   at VpnHood.Client.VpnHoodClient.SendRequest[T](ClientRequest request, CancellationToken cancellationToken) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Client\VpnHoodClient.cs:line 801
   at VpnHood.Client.VpnHoodClient.ConnectInternal(CancellationToken cancellationToken, Boolean redirecting) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Client\VpnHoodClient.cs:line 601
   at VpnHood.Client.VpnHoodClient.Connect() in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Client\VpnHoodClient.cs:line 234

Trac 
| 19:01:27.4405 |  | Shutting down...

Info 
| 19:01:27.4405 |  | Client state is changed. NewState: Disconnecting

Trac 
| 19:01:27.4427 |  | Disposing ClientHost...

Trac 
| 19:01:27.4427 |  | Disposing Tunnel...

Trac 
| 19:01:27.4428 |  | Disposing ProxyManager...

Trac 
| 19:01:27.4428 |  | Disposing Nat...

Trac 
| 19:01:27.4428 |  | Disposing ConnectorService...

Info 
| 19:01:27.4428 |  | Client state is changed. NewState: Disposed

Info 
| 19:01:27.4444 |  | Bye Bye!

Erro 
| 19:01:27.4445 |  | Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.

**Comment by trudyhood** [comment]
It means the server is down or unreachable. Is it your own server?

**Comment by Keiser04** [comment]
> It means the server is down or unreachable. Is it your own server?

yes it is

**Comment by Keiser04** [comment]
@trudyhood i am using a virtual box ubuntu server. later was working but after 1 week no

**Comment by Keiser04** [comment]
nvm now it works after get a new key
