### ISSUE TITLE
Unable to run Android Samples in Android Emulator

### ISSUE THREAD

**Issue by karnilamit** [vpnhood/VpnHood#54]
Hi there,

I having been trying to run the Android Sample in an Android Emulator but couldn't do so. The app crashes while launching. The Android App does run fine though.

Below is the snippet of logs for the crash
```
> am start -a "android.intent.action.MAIN" -c "android.intent.category.LAUNCHER" -n "com.vpnhood.samples.simpleclient.droid/crc645e76e89519cc4178.MainActivity"
> Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.vpnhood.samples.simpleclient.droid/crc645e76e89519cc4178.MainActivity }
[pleclient.droi] Not late-enabling -Xcheck:jni (already on)
[pleclient.droi] Unexpected CPU variant for X86 using defaults: x86
[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.vpnhood.samples.simpleclient.droid, PID: 10172
[AndroidRuntime] java.lang.RuntimeException: Unable to instantiate application com.vpnhood.samples.simpleclient.droid.VpnHood: java.lang.ClassNotFoundException: Didn't find class "com.vpnhood.samples.simpleclient.droid.VpnHood" on path: DexPathList[[zip file "/data/app/com.vpnhood.samples.simpleclient.droid-1JDg_b7bemibub6TErY2-A==/base.apk"],nativeLibraryDirectories=[/data/app/com.vpnhood.samples.simpleclient.droid-1JDg_b7bemibub6TErY2-A==/lib/x86, /data/app/com.vpnhood.samples.simpleclient.droid-1JDg_b7bemibub6TErY2-A==/base.apk!/lib/x86, /system/lib]]
[AndroidRuntime] 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1069)
[AndroidRuntime] 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5842)
[AndroidRuntime] 	at android.app.ActivityThread.access$1100(ActivityThread.java:199)
[AndroidRuntime] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:193)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:6669)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
[AndroidRuntime] Caused by: java.lang.ClassNotFoundException: Didn't find class "com.vpnhood.samples.simpleclient.droid.VpnHood" on path: DexPathList[[zip file "/data/app/com.vpnhood.samples.simpleclient.droid-1JDg_b7bemibub6TErY2-A==/base.apk"],nativeLibraryDirectories=[/data/app/com.vpnhood.samples.simpleclient.droid-1JDg_b7bemibub6TErY2-A==/lib/x86, /data/app/com.vpnhood.samples.simpleclient.droid-1JDg_b7bemibub6TErY2-A==/base.apk!/lib/x86, /system/lib]]
[AndroidRuntime] 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
[AndroidRuntime] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
[AndroidRuntime] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
[AndroidRuntime] 	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:50)
[AndroidRuntime] 	at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
[AndroidRuntime] 	at android.app.Instrumentation.newApplication(Instrumentation.java:1120)
[AndroidRuntime] 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1061)
[AndroidRuntime] 	... 9 more
[Process] Sending signal. PID: 10172 SIG: 9

```

Any clue what could be wrong? The windows sample runs fine.

Thanks,
A.K.

**Comment by karnilamit** [comment]
Tried the sample app on an android device ( a Samsung M21phone) and it still crashes.

**Comment by trudyhood** [comment]
Dear @karnilamit 
Thank you for reporting it.

It looked it just decided to get crazy suddenly :)
I have updated the sample on the main branch, you can download/update the sample again.

Or you can fix manually by opening AndroidManifest.xml and delete this: 

`android:name="VpnHood"`

![image](https://user-images.githubusercontent.com/72891124/135820757-7f0c15c9-5c45-4450-a9bf-06ba743e5d1c.png)

Please let me know if you encounter any other issue.

**Comment by karnilamit** [comment]
Thanks that did the trick. I am able to run the sample now.
