### ISSUE TITLE
Run server on LAN

### ISSUE THREAD

**Issue by DUOLabs333** [vpnhood/VpnHood#72]
I want to run VPNHood on my LAN. The problem is, when it starts, it binds to my LAN address, but the key created is for my public address (192.168.x.x vs 72.x.x.x). So is it possible to make the key only for the LAN address?

**Comment by trudyhood** [comment]
Yes, it is possible. I added a short document for you:
https://github.com/vpnhood/VpnHood/wiki/How-to-change-VpnHood-ServerIp-in-access-key

Feel free to re-open this issue if it doesn't work as you expected.

**Comment by DUOLabs333** [comment]
I can't reopen it (since you closed it), but it still doesn't want to connect with "Connection refused". I tried to diagnose it, but it failed to open the log.txt

**Comment by trudyhood** [comment]
> I can't reopen it (since you closed it), but it still doesn't want to connect with "Connection refused". I tried to diagnose it, but it failed to open the log.txt

What is your client device? (Windows or Android)
Are you be able to connect to our public server?

**Comment by DUOLabs333** [comment]
The public server works. The client is Android.

**Comment by trudyhood** [comment]
Thank you for keep contacting us. I am committed to find and solve the issue.

1. Are you sure you client has access to your Local server? 
2. What error you get when you try to Diagnose it?
3. What is your Client Version?
4. Can you share your server log?

**Comment by DUOLabs333** [comment]
Got it to work on my machine, but I can't access any service local to my machine (I have a service running on localhost:5000, but I can't access that in Chrome).

**Comment by trudyhood** [comment]
So you don't have access your local services on other machine! 
1) I think your WiFi router may have "client isolation on". It is a feature that prevent other client to access each other on same WiFi network. Make sure it is off.
2. Make sure your server firewall is off

**Comment by trudyhood** [comment]
Is your server firewall off? Maybe the SOCKS proxy already opened it for itself. VpnHood server does not touch server FireWall ports. Would you turn it off?

**Comment by DUOLabs333** [comment]
My firewall is off.

**Comment by trudyhood** [comment]
Can you access your SOCKS proxy by your Android phone?

**Comment by trudyhood** [comment]
Can you share the log of VpnHood server?

**Comment by DUOLabs333** [comment]
```
021-11-15 11:53:46.5601 | Info | Server => RemoteEp: 192.168.1.90:39773 => SessionId: 5** StreamChannel 
 A TcpProxyChannel has been removed. ChannelCount: 7  

2021-11-15 11:53:50.6619 | Info | Server => RemoteEp: 192.168.1.90:39967 Tcp 
 TLS Authenticating. CertSubject: CN=sha.doshopaezhy.net...  

2021-11-15 11:53:50.6948 | Info | Server => RemoteEp: 192.168.1.90:39967 Hello 
 Processing hello request... ClientEp: 192.168.1.90:39967  

2021-11-15 11:53:50.6970 | Info | Server => RemoteEp: 192.168.1.90:39967 Hello 
 Creating Session... TokenId: 09509**, ClientId: 8647c**, ClientVersion: 2.2.283  

2021-11-15 11:53:50.6988 | Info | Server => RemoteEp: 192.168.1.90:39967 Udp 
 Creating a UdpChannel. SessionId: 0 ...  

2021-11-15 11:53:50.6988 | Info | Server => RemoteEp: 192.168.1.90:39967 DatagramChannel 
 A UdpChannel has been added. ChannelCount: 1  

2021-11-15 11:53:50.6988 | Info | Server => RemoteEp: 192.168.1.90:39967  
 New session has been created. SessionId: 8  

2021-11-15 11:53:50.7785 | Info | Server => RemoteEp: 192.168.1.90:39967 => UdpProxy, LocalPort: 43144 Udp 
 A UdpProxy has been created. LocalEp: 0.0.0.0:43144  

2021-11-15 11:53:50.7785 | Info | Server => RemoteEp: 192.168.1.90:39967 => UdpProxy, LocalPort: 43144 => UdpProxy LocalEp: 0.0.0.0:43144 Udp 
 Start listening...  

2021-11-15 11:53:50.8417 | Info | Server => RemoteEp: 192.168.1.90:43491 Tcp 
 TLS Authenticating. CertSubject: CN=sha.doshopaezhy.net...  

2021-11-15 11:53:50.8867 | Info | Server => RemoteEp: 192.168.1.90:43491 StreamChannel 
 Reading the TcpProxyChannel request...  

2021-11-15 11:53:50.8941 | Info | Server => RemoteEp: 192.168.1.90:39967 => UdpProxy, LocalPort: 43971 Udp 
 A UdpProxy has been created. LocalEp: 0.0.0.0:43971  

2021-11-15 11:53:50.8941 | Info | Server => RemoteEp: 192.168.1.90:39967 => UdpProxy, LocalPort: 43971 => UdpProxy LocalEp: 0.0.0.0:43971 Udp 
 Start listening...  

2021-11-15 11:53:50.8948 | Error | Server => RemoteEp: 192.168.1.90:39967  
 Packets dropped! Error in processing channel received packets. Message: System.IO.InvalidDataException: Invalid UDP packet! It is: Udp
   at VpnHood.Tunneling.PacketUtil.ExtractUdp(IPPacket ipPacket) in C:\Users\Robert\Source\Repos\Vh\VpnHood\VpnHood.Tunneling\PacketUtil.cs:line 129
   at VpnHood.Tunneling.NatItem..ctor(IPPacket ipPacket) in C:\Users\Robert\Source\Repos\Vh\VpnHood\VpnHood.Tunneling\NatItem.cs:line 23
   at VpnHood.Tunneling.Nat.CreateNatItemFromPacket(IPPacket ipPacket) in C:\Users\Robert\Source\Repos\Vh\VpnHood\VpnHood.Tunneling\Nat.cs:line 47
   at VpnHood.Tunneling.Nat.Get(IPPacket ipPacket) in C:\Users\Robert\Source\Repos\Vh\VpnHood\VpnHood.Tunneling\Nat.cs:line 119
   at VpnHood.Tunneling.ProxyManager.SendUdpPacket(IPPacket ipPacket) in C:\Users\Robert\Source\Repos\Vh\VpnHood\VpnHood.Tunneling\ProxyManager.cs:line 117
   at VpnHood.Tunneling.ProxyManager.SendPacket(IEnumerable`1 ipPackets) in C:\Users\Robert\Source\Repos\Vh\VpnHood\VpnHood.Tunneling\ProxyManager.cs:line 61
   at VpnHood.Tunneling.Tunnel.Channel_OnPacketReceived(Object sender, ChannelPacketReceivedEventArgs e) in C:\Users\Robert\Source\Repos\Vh\VpnHood\VpnHood.Tunneling\Tunnel.cs:line 272  

2021-11-15 11:53:50.8987 | Error | Server => RemoteEp: 192.168.1.90:39967  
 Packets dropped! Error in processing channel received packets. Message: System.IO.InvalidDataException: Invalid UDP packet! It is: Udp
   at VpnHood.Tunneling.PacketUtil.ExtractUdp(IPPacket ipPacket) in C:\Users\Robert\Source\Repos\Vh\VpnHood\VpnHood.Tunneling\PacketUtil.cs:line 129
   at VpnHood.Tunneling.NatItem..ctor(IPPacket ipPacket) in C:\Users\Robert\Source\Repos\Vh\VpnHood\VpnHood.Tunneling\NatItem.cs:line 23
   at VpnHood.Tunneling.Nat.CreateNatItemFromPacket(IPPacket ipPacket) in C:\Users\Robert\Source\Repos\Vh\VpnHood\VpnHood.Tunneling\Nat.cs:line 47
   at VpnHood.Tunneling.Nat.Get(IPPacket ipPacket) in C:\Users\Robert\Source\Repos\Vh\VpnHood\VpnHood.Tunneling\Nat.cs:line 119
   at VpnHood.Tunneling.ProxyManager.SendUdpPacket(IPPacket ipPacket) in C:\Users\Robert\Source\Repos\Vh\VpnHood\VpnHood.Tunneling\ProxyManager.cs:line 117
   at VpnHood.Tunneling.ProxyManager.SendPacket(IEnumerable`1 ipPackets) in C:\Users\Robert\Source\Repos\Vh\VpnHood\VpnHood.Tunneling\ProxyManager.cs:line 61
   at VpnHood.Tunneling.Tunnel.Channel_OnPacketReceived(Object sender, ChannelPacketReceivedEventArgs e) in C:\Users\Robert\Source\Repos\Vh\VpnHood\VpnHood.Tunneling\Tunnel.cs:line 272  

2021-11-15 11:53:50.9166 | Info | Server => RemoteEp: 192.168.1.90:39967 => UdpProxy, LocalPort: 53208 Udp 
 A UdpProxy has been created. LocalEp: 0.0.0.0:53208  

2021-11-15 11:53:50.9166 | Info | Server => RemoteEp: 192.168.1.90:39967 => UdpProxy, LocalPort: 53208 => UdpProxy LocalEp: 0.0.0.0:53208 Udp 
 Start listening...  

2021-11-15 11:53:50.9361 | Info | Server => RemoteEp: 192.168.1.90:39967 => UdpProxy, LocalPort: 43685 Udp 
 A UdpProxy has been created. LocalEp: 0.0.0.0:43685  

2021-11-15 11:53:50.9361 | Info | Server => RemoteEp: 192.168.1.90:39967 => UdpProxy, LocalPort: 43685 => UdpProxy LocalEp: 0.0.0.0:43685 Udp 
 Start listening...  

2021-11-15 11:53:50.9572 | Info | Server => RemoteEp: 192.168.1.90:39967 => UdpProxy, LocalPort: 39840 Udp 
 A UdpProxy has been created. LocalEp: 0.0.0.0:39840  

2021-11-15 11:53:50.9572 | Info | Server => RemoteEp: 192.168.1.90:39967 => UdpProxy, LocalPort: 39840 => UdpProxy LocalEp: 0.0.0.0:39840 Udp 
 Start listening...  

2021-11-15 11:53:50.9648 | Info | Server => RemoteEp: 192.168.1.90:39967 => UdpProxy, LocalPort: 53673 Udp 
 A UdpProxy has been created. LocalEp: 0.0.0.0:53673  

2021-11-15 11:53:50.9648 | Info | Server => RemoteEp: 192.168.1.90:39967 => UdpProxy, LocalPort: 53673 => UdpProxy LocalEp: 0.0.0.0:53673 Udp 
 Start listening...  

2021-11-15 11:53:50.9718 | Info | Server => RemoteEp: 192.168.1.90:43491 => SessionId: 8** StreamChannel 
 A TcpProxyChannel has been added. ChannelCount: 1  

2021-11-15 11:53:50.9961 | Info | Server => RemoteEp: 192.168.1.90:39967 => UdpProxy, LocalPort: 45089 Udp 
 A UdpProxy has been created. LocalEp: 0.0.0.0:45089  

2021-11-15 11:53:50.9961 | Info | Server => RemoteEp: 192.168.1.90:39967 => UdpProxy, LocalPort: 45089 => UdpProxy LocalEp: 0.0.0.0:45089 Udp 
 Start listening...  

2021-11-15 11:53:50.9981 | Info | Server => RemoteEp: 192.168.1.90:39967 => UdpProxy, LocalPort: 58188 Udp 
 A UdpProxy has been created. LocalEp: 0.0.0.0:58188  

2021-11-15 11:53:50.9981 | Info | Server => RemoteEp: 192.168.1.90:39967 => UdpProxy, LocalPort: 58188 => UdpProxy LocalEp: 0.0.0.0:58188 Udp 
 Start listening...  

2021-11-15 11:53:51.0358 | Info | Server => RemoteEp: 192.168.1.90:40923 Tcp 
 TLS Authenticating. CertSubject: CN=sha.doshopaezhy.net...  

2021-11-15 11:53:51.1271 | Info | Server => RemoteEp: 192.168.1.90:40923 StreamChannel 
 Reading the TcpProxyChannel request...  

2021-11-15 11:53:51.1491 | Info | Server => RemoteEp: 192.168.1.90:40923 => SessionId: 8** StreamChannel 
 A TcpProxyChannel has been added. ChannelCount: 2  

2021-11-15 11:53:51.2693 | Info | Server => RemoteEp: 192.168.1.90:39967 => UdpProxy, LocalPort: 42209 Udp 
 A UdpProxy has been created. LocalEp: 0.0.0.0:42209  

2021-11-15 11:53:51.2693 | Info | Server => RemoteEp: 192.168.1.90:39967 => UdpProxy, LocalPort: 42209 => UdpProxy LocalEp: 0.0.0.0:42209 Udp 
 Start listening...  

2021-11-15 11:53:51.2693 | Info | Server => RemoteEp: 192.168.1.90:39967 => UdpProxy, LocalPort: 48021 Udp 
 A UdpProxy has been created. LocalEp: 0.0.0.0:48021  

2021-11-15 11:53:51.2693 | Info | Server => RemoteEp: 192.168.1.90:39967 => UdpProxy, LocalPort: 48021 => UdpProxy LocalEp: 0.0.0.0:48021 Udp 
 Start listening...  

2021-11-15 11:53:51.3147 | Info | Server => RemoteEp: 192.168.1.90:38403 Tcp 
 TLS Authenticating. CertSubject: CN=sha.doshopaezhy.net...  

2021-11-15 11:53:51.3454 | Info | Server => RemoteEp: 192.168.1.90:38403 StreamChannel 
 Reading the TcpProxyChannel request...  

2021-11-15 11:53:51.3625 | Info | Server => RemoteEp: 192.168.1.90:38403 => SessionId: 8** StreamChannel 
 A TcpProxyChannel has been added. ChannelCount: 3  

2021-11-15 11:53:51.8012 | Info | Server => RemoteEp: 192.168.1.90:37887 Tcp 
 TLS Authenticating. CertSubject: CN=sha.doshopaezhy.net...  

2021-11-15 11:53:51.8353 | Info | Server => RemoteEp: 192.168.1.90:37887 StreamChannel 
 Reading the TcpProxyChannel request...  

2021-11-15 11:53:51.9203 | Info | Server => RemoteEp: 192.168.1.90:37887 => SessionId: 8** StreamChannel 
 A TcpProxyChannel has been added. ChannelCount: 4  

2021-11-15 11:53:54.5371 | Info | Server => RemoteEp: 192.168.1.90:39967 => UdpProxy, LocalPort: 50548 Udp 
 A UdpProxy has been created. LocalEp: 0.0.0.0:50548  

2021-11-15 11:53:54.5377 | Info | Server => RemoteEp: 192.168.1.90:39967 => UdpProxy, LocalPort: 50548 => UdpProxy LocalEp: 0.0.0.0:50548 Udp 
 Start listening...  

2021-11-15 11:53:54.5377 | Info | Server => RemoteEp: 192.168.1.90:39967 => UdpProxy, LocalPort: 48776 Udp 
 A UdpProxy has been created. LocalEp: 0.0.0.0:48776  

2021-11-15 11:53:54.5387 | Info | Server => RemoteEp: 192.168.1.90:39967 => UdpProxy, LocalPort: 48776 => UdpProxy LocalEp: 0.0.0.0:48776 Udp 
 Start listening...  

2021-11-15 11:53:56.4013 | Info | Server => RemoteEp: 192.168.1.90:39729 Tcp 
 TLS Authenticating. CertSubject: CN=sha.doshopaezhy.net...  

2021-11-15 11:53:56.4487 | Info | Server => RemoteEp: 192.168.1.90:39729 StreamChannel 
 Reading the TcpProxyChannel request...  

2021-11-15 11:53:56.4598 | Info | Server => RemoteEp: 192.168.1.90:39729 => SessionId: 8** StreamChannel 
 A TcpProxyChannel has been added. ChannelCount: 5 
```

**Comment by trudyhood** [comment]
Thank you.
But it looks it is working! How do you get Connection Refused from client? Do you get that error after connecting to your server by VpnHood client

**Comment by DUOLabs333** [comment]
Yes -- typing in `0.0.0.0:$PORT` fails

**Comment by trudyhood** [comment]
Sorry, but I can't understand "typing in 0.0.0.0:$PORT"
Where do you type it?

**Comment by DUOLabs333** [comment]
In Chrome or any browser. For example, 0.0.0.0:5000 on the client if you have a service running on 127.0.0.1:5000 on the server.

**Comment by trudyhood** [comment]
You can't connect to any service via "127.0.0.1" ip. it is loopback address works on each machine for itself and not accessible by other machine, try finding your server Local IP address such as 192.168.x.x
Also you can not connect to any service via "0.0.0.0". it is an invalid address

**Comment by DUOLabs333** [comment]
Then why does it work on my Macbook?

**Comment by trudyhood** [comment]
If you type 127.0.0.1 and get any result, it means there is a proxy or a service running on your Mackbook. maybe that proxy connect to your server and delegate your traffic there, but 127.0.0.1 is for client.
If you type 0.0.0.0 and get any result, it means I have to study more about network :)

**Comment by DUOLabs333** [comment]
For my Macbook, 0.0.0.0 works as well.

**Comment by trudyhood** [comment]
I searched it now. It look 0.0.0.0 is an alias for 127.0.0.01 in Macbook. Which means Macbook actively replace it with 127.0.0.1
https://apple.stackexchange.com/questions/366390/how-why-do-0-0-0-0-connections-get-a-response

**Comment by DUOLabs333** [comment]
I guess that makes sense -- Chrome mobile doesn't allow localhost to go through VPNs, and for some reason, VPNHood doesn't use my server's DNS, which has some rewriting in place.

**Comment by trudyhood** [comment]
You should be connected if you set your server local IP. try to find your server local IP.

**Comment by trudyhood** [comment]
I am wondering why you are trying to use VpnHood. Is that because your local server have access to Internet but other machines on your local network do not have access?

**Comment by DUOLabs333** [comment]
I'm trying to use it to connect to my server's local services without exposing it to the internet.

**Comment by trudyhood** [comment]
So are you trying to connect to your server's local service from internet without exposing it  to others? I mean is your client connect to your server via public internet?

**Comment by DUOLabs333** [comment]
So my server's services are local only. I want to connect to my server publicly to access those local services.

**Comment by DUOLabs333** [comment]
So basically my client acts like the remote server.

**Comment by DUOLabs333** [comment]
Still doesn't work, though now it says Empty response, not Connection refused.

**Comment by trudyhood** [comment]
Who says that? your browser or VpnHood client?

**Comment by DUOLabs333** [comment]
The browser.

**Comment by trudyhood** [comment]
Can I ask what do you type is your browser address. You should know it is not important to share local IPs in public. All local networks shares same IP range. Make sure not to post your public IP address here

**Comment by DUOLabs333** [comment]
I type in `192.168.x.x:5000`

**Comment by trudyhood** [comment]
OK, I am going to understand the issue. Let first check your network service without any proxy. Is your client connected to same local work? In that case you should be able to connect to your server via 192.168.x.x:5000 without any proxy. Can you do that?

**Comment by DUOLabs333** [comment]
No, because that service is only on 127.0.0.1 on the server

**Comment by trudyhood** [comment]
So, If you want to share your service to other client in you local network but not public you need to make it run on your local IP (Not Loopback).

**Comment by DUOLabs333** [comment]
Oh, I was trying to use a VPN to avoid that.

**Comment by trudyhood** [comment]
I am not sure, but I think you misunderstand something here. It is a common scenario to run local services and prevent public access but VPN users. But If you want to run your service on your local IP, you need to bind it on your local IP and block its access from public IP by firewall. I can understand you try to achieve that by 127.0.0.1, but it is the wrong way. 

I think your server public address is mapped to your server local IP address, so you are worried that people can connect to your service via your Public Address if you run the service on your local IP address, so you ended up choosing 127.0.0.1, but it is the wrong strategy, you need to assign another local IP address on your server. a machine can have a many local ip addresses such as 192.168.1.10, 192.168.1.11, 192.168.1.12. You need to run your service on a local IP address not mapped to your public address, but not 127.0.0.1. 

After that you can choose any VPN or proxies to achieve your goal.

**Comment by DUOLabs333** [comment]
I tried binding my reverse proxy to 192.168.1.67, but nothing came up.

**Comment by DUOLabs333** [comment]
It seems that I don't have the permission to bind it.

**Comment by trudyhood** [comment]
Could you run VpnHood server on 192.168.1.67?

**Comment by DUOLabs333** [comment]
No.

**Comment by trudyhood** [comment]
What is the error?

**Comment by DUOLabs333** [comment]
"Message: Cannot assign requested address"

**Comment by trudyhood** [comment]
OH!, You need to configure your server for that IP First!

**Comment by DUOLabs333** [comment]
But I though I can push to multiple IP addresses.

**Comment by trudyhood** [comment]
I know it might be advanced topic, but you need to add another IP address to your LAN. There are many documents and tutorial on net, such as this
https://linuxhint.com/how-to-assign-multiple-ip-addresses-to-single-nic-in-ubuntu-20-04-lts/

**Comment by DUOLabs333** [comment]
It works! Thank you so much for the article.

**Comment by trudyhood** [comment]
Great! Could you manage to connect to your server via VpnHood?

**Comment by DUOLabs333** [comment]
Just one question -- If I move to a different network, will the newly added IP go away or change, or will only the primary address?

**Comment by trudyhood** [comment]
It depends on how to move to another network, but I think it will not be changed. Even if it gets altered for any reason, you can add it again regardless of your network configuration. Make sure you set a Local IP that does not conflict with other machines in your local network.

**Comment by DUOLabs333** [comment]
Ok, I'm almost done fixing all the errors, but there's something that bugs me -- `dig @192.168.x.x $LOCALDOMAIN gives the right IP address`, but doing `curl --dns-servers 192.168.1.67 $LOCALDOMAIN` fails.

**Comment by trudyhood** [comment]
Is it after your client connected to VpnHood Server?

**Comment by DUOLabs333** [comment]
No, I'm trying to set everything up before connecting.

**Comment by trudyhood** [comment]
so perhaps you don't have any DNS server service on 192.168.1.67. 
It is the VPN client job to map that for you, you don't need to set up that.
Try to connect to VpnHood server and surf something via IP address, if this work we can go to next step.

**Comment by DUOLabs333** [comment]
Got it to work (forgot to update the domains) -- thank you so much.

**Comment by trudyhood** [comment]
I believe we need to be able to specify DNS server on VpnHood server. I believe it will not work if your clients connect to your VpnHood server via its public IP, because VpnHood maps DNS requests to 8.8.8.8, so your client will not be able to resolve IPs for your local machines. 

I have created an issue with it. Please post a comment on that issue if you think we have to prioritize it.
https://github.com/vpnhood/VpnHood/issues/73

**Comment by DUOLabs333** [comment]
One problem: while `ip addr add` works on my own Wifi, when I switched to another network, `192.168.1.67` no longer works.

**Comment by trudyhood** [comment]
Could you please give me more information. 

- What does not work? 
- What is the address of other network? 
- How these two network connected to each others?

**Comment by DUOLabs333** [comment]
I can successfully set the IP `192.168.1.67` on my local machine. However, nothing can connect to it. It is important to note that all machines follow `192.168.6.x`, rather than `192.168.1.x`

**Comment by trudyhood** [comment]
You should run VpnHood server on 192.168.6.x, and run your actual service on 192.168.1.x.
Perhaps you need to study more about computer networking.
